name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }} 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $GITHUB_REPOSITORY:$GITHUB_RUN_NUMBER
    - name: Docker push image
      run: docker push $GITHUB_REPOSITORY:$GITHUB_RUN_NUMBER
    - name: Docker tag latest image
      run: docker tag $GITHUB_REPOSITORY:$GITHUB_RUN_NUMBER $GITHUB_REPOSITORY:latest
    - name: Docker push latest image
      run: docker push $GITHUB_REPOSITORY:latest
